version: '3.8'

services:
  # meteor-app:
  #   environment:
  #     - NODE_ENV=production
  #     - DEV=true
  #     - DATABASE_URL=mysql://sql-username:sql-password@meteor-db/meteor
  #     - S3_ENDPOINT=minio
  #     - S3_BUCKET=meteor
  #     - S3_PORT=9000
  #     - S3_ACCESS_KEY=S3-ACCESS-KEY
  #     - S3_SECRET_KEY=S3-SECRET-KEY
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - meteor-network
  #   depends_on:
  #     - minio

  meteor-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=meteor
      - MYSQL_USER=sql-username
      - MYSQL_PASSWORD=sql-password
    ports:
      - "3306:3306"
    networks:
      - meteor-network

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_REGION_NAME: 'eu-central-1'
    command: minio server --console-address ":9001" /data
    networks:
      - meteor-network

networks:
  meteor-network:
    driver: bridge

volumes:
  minio-data:
    driver: local
